language: perl

perl:
  - "5.8"
  - "5.10"
  - "5.12"

services:
  - memcached

before_install:
  # Install Berkeley DB for installing DB_File module.
  # libperl-dev for installing ImageMagick.
  # php5, php5-mysql, php5-gd for tests of dynamic publishing.
  # libpng12-dev, libgif-dev and libjpeg-dev for Imager.
  - sudo apt-get install libdb-dev libgd2-xpm-dev libgmp3-dev libperl-dev php5 php5-mysql php5-gd libpng12-dev libgif-dev libjpeg-dev

install:
  # Install ImageMagick for installing Image::Magick.
  - mkdir local
  - cd local
  - wget http://www.imagemagick.org/download/ImageMagick-6.8.9-10.tar.gz
  - tar xzvf ImageMagick-6.8.9-10.tar.gz
  - cd ImageMagick-6.8.9-10
  - ./configure --prefix=${HOME}/local --with-perl=${HOME}/perl5/perlbrew/perls/${TRAVIS_PERL_VERSION}/bin/perl
  - make
  - sudo make install
  - cd ../../

  # Instal CPAN modules.
  - cpanm -n Crypt::CBC
  - travis_retry cpanm -n --installdeps . --cpanfile ./t/cpanfile

  # Build MT.
  #- SHELL=/bin/bash make me

before_script:
  # Create MySQL database for tests.
  - mysql -e "create database mt_test;"
  - mysql -uroot -e "grant all privileges on mt_test.* to mt@localhost;"

  # Some tests need mt-config.cgi.
  - cp ./t/mysql-test.cfg ./mt-config.cgi

script:
  - "prove ./t ./plugins/*/t"

